const esbuild = require("esbuild");
const fs = require("fs");
const path = require("path");

const watch = process.argv.includes("--watch");

const ROOT = __dirname;

/* -------------------------------------------------------------------------- */
/* esbuild configuration                                                      */
/* -------------------------------------------------------------------------- */

const options = {
  entryPoints: {
    background: "./background.ts",
    content: "./content.ts",
    blocked: "./blocked.ts",
  },

  outdir: ".",

  bundle: true,

  format: "esm",

  platform: "browser",

  target: ["chrome120"],

  sourcemap: false,

  logLevel: "info",
};

/* -------------------------------------------------------------------------- */
/* Static extension assets                                                    */
/* -------------------------------------------------------------------------- */

/**
 * Files required by the Chrome/Edge extension but not generated by esbuild.
 */
const STATIC_FILES = [
  "manifest.json",
  "blocked.html",
  "blocked.css",
];

/**
 * Static directories required by the extension.
 */
const STATIC_DIRECTORIES = [
  "icons",
];

/**
 * Copy a file if it exists.
 */
function copyFileIfExists(fileName) {
  const source = path.join(ROOT, fileName);
  const destination = path.join(ROOT, fileName);

  if (!fs.existsSync(source)) {
    console.warn(
      `⚠️ Static file not found: ${fileName}`
    );

    return false;
  }

  /*
   * Source and destination are the same because the extension
   * build output lives in the extension root.
   *
   * We still verify the file exists so the build fails loudly
   * when an important resource is missing.
   */
  if (!fs.statSync(source).isFile()) {
    console.warn(
      `⚠️ Expected file but found something else: ${fileName}`
    );

    return false;
  }

  console.log(`📦 Static file ready: ${fileName}`);

  return true;
}

/**
 * Verify a static directory exists.
 */
function verifyDirectory(directoryName) {
  const directory = path.join(
    ROOT,
    directoryName
  );

  if (!fs.existsSync(directory)) {
    console.warn(
      `⚠️ Static directory not found: ${directoryName}`
    );

    return false;
  }

  if (!fs.statSync(directory).isDirectory()) {
    console.warn(
      `⚠️ Expected directory but found something else: ${directoryName}`
    );

    return false;
  }

  console.log(
    `📦 Static directory ready: ${directoryName}`
  );

  return true;
}

/* -------------------------------------------------------------------------- */
/* Validate extension resources                                               */
/* -------------------------------------------------------------------------- */

function verifyExtensionResources() {
  console.log(
    "\n🔎 Checking Resolve extension resources..."
  );

  let valid = true;

  for (const file of STATIC_FILES) {
    const exists = copyFileIfExists(file);

    /*
     * blocked.html is mandatory because DNR redirects
     * blocked navigation to this resource.
     */
    if (
      file === "blocked.html" &&
      !exists
    ) {
      valid = false;
    }
  }

  for (const directory of STATIC_DIRECTORIES) {
    verifyDirectory(directory);
  }

  if (!valid) {
    throw new Error(
      [
        "",
        "❌ Resolve extension build cannot continue.",
        "",
        "blocked.html is missing.",
        "",
        "The DNR blocker redirects blocked websites to:",
        "    /blocked.html",
        "",
        "Therefore apps/extension/blocked.html must exist.",
        "",
        `Expected location: ${path.join(
          ROOT,
          "blocked.html"
        )}`,
        "",
      ].join("\n")
    );
  }

  console.log(
    "✅ Required extension resources are present."
  );
}

/* -------------------------------------------------------------------------- */
/* Build                                                                      */
/* -------------------------------------------------------------------------- */

async function run() {
  try {
    console.log(
      "\n🛡️ Building Resolve Recovery extension..."
    );

    /*
     * Check static files before esbuild.
     */
    verifyExtensionResources();

    /*
     * Build TypeScript entry points.
     */
    if (watch) {
      const ctx =
        await esbuild.context(options);

      await ctx.watch();

      console.log(
        "👀 Resolve extension watching..."
      );
    } else {
      await esbuild.build(options);

      console.log(
        "\n📦 Generated extension scripts:"
      );

      console.log(
        "   ✓ background.js"
      );

      console.log(
        "   ✓ content.js"
      );

      console.log(
        "   ✓ blocked.js"
      );

      console.log(
        "\n📦 Static extension resources:"
      );

      console.log(
        "   ✓ manifest.json"
      );

      console.log(
        "   ✓ blocked.html"
      );

      console.log(
        "   ✓ blocked.css"
      );

      console.log(
        "   ✓ icons/"
      );

      console.log(
        "\n✅ Resolve extension build complete."
      );
    }
  } catch (err) {
    console.error(
      "\n❌ Resolve extension build failed:"
    );

    console.error(err);

    process.exit(1);
  }
}

run();