/**
 * Resolve Declarative Net Request Blocking Engine
 *
 * Redirects blocked websites to:
 *
 *   /blocked.html?site=example.com
 *
 * instead of showing the browser's generic
 * ERR_BLOCKED_BY_CLIENT page.
 */

const MAX_DYNAMIC_RULES = 30_000;

/**
 * Resolve owns:
 *
 * 100000 → 129999
 */
const RESOLVE_RULE_ID_START = 100_000;

/* -------------------------------------------------------------------------- */
/* Get Rules                                                                  */
/* -------------------------------------------------------------------------- */

export async function getBlockingRules(): Promise<
  chrome.declarativeNetRequest.Rule[]
> {
  try {
    if (!chrome.declarativeNetRequest) {
      throw new Error(
        "Declarative Net Request API is unavailable."
      );
    }

    return await chrome.declarativeNetRequest.getDynamicRules();
  } catch (error) {
    console.error(
      "❌ Failed to get Resolve blocking rules:",
      error
    );

    return [];
  }
}

/* -------------------------------------------------------------------------- */
/* Resolve Rule Detection                                                     */
/* -------------------------------------------------------------------------- */

function isResolveRule(
  rule: chrome.declarativeNetRequest.Rule
): boolean {
  /**
   * Current Resolve rules.
   */
  const hasResolveId =
    rule.id >= RESOLVE_RULE_ID_START &&
    rule.id <
      RESOLVE_RULE_ID_START +
        MAX_DYNAMIC_RULES;

  /**
   * Rules generated by older versions of Resolve
   * that redirected to blocked.html.
   */
  const isOldResolveRedirect =
    rule.action?.type === "redirect" &&
    rule.action.redirect?.extensionPath ===
      "/blocked.html";

  return (
    hasResolveId ||
    isOldResolveRedirect
  );
}

/* -------------------------------------------------------------------------- */
/* Clear Resolve Rules                                                        */
/* -------------------------------------------------------------------------- */

export async function clearBlockingRules(): Promise<void> {
  if (!chrome.declarativeNetRequest) {
    throw new Error(
      "Declarative Net Request API is unavailable."
    );
  }

  const existingRules =
    await chrome.declarativeNetRequest.getDynamicRules();

  const resolveRules =
    existingRules.filter(
      isResolveRule
    );

  if (resolveRules.length === 0) {
    console.log(
      "🧹 No Resolve rules to remove."
    );

    return;
  }

  const removeRuleIds =
    resolveRules.map(
      (rule) => rule.id
    );

  await chrome.declarativeNetRequest.updateDynamicRules({
    removeRuleIds,
  });

  console.log(
    `🧹 Removed ${removeRuleIds.length} Resolve rules.`
  );
}

/* -------------------------------------------------------------------------- */
/* Domain Normalization                                                       */
/* -------------------------------------------------------------------------- */

function normalizeDomain(
  value: string
): string {
  let domain =
    value.trim().toLowerCase();

  if (!domain) {
    return "";
  }

  /**
   * Remove protocol.
   */
  domain = domain.replace(
    /^https?:\/\//,
    ""
  );

  /**
   * Remove www.
   */
  domain = domain.replace(
    /^www\./,
    ""
  );

  /**
   * Remove path.
   */
  domain =
    domain.split("/")[0];

  /**
   * Remove port.
   */
  domain =
    domain.split(":")[0];

  return domain.trim();
}

/* -------------------------------------------------------------------------- */
/* Build Resolve Redirect URL                                                 */
/* -------------------------------------------------------------------------- */

/**
 * Build the URL of Resolve's blocked page.
 *
 * Example:
 *
 * chrome-extension://EXTENSION_ID/blocked.html?site=betika.com
 *
 * We use chrome.runtime.getURL() so we never hard-code
 * the extension ID.
 */
function buildBlockedPageUrl(
  domain: string
): string {
  const blockedPage =
    chrome.runtime.getURL(
      "blocked.html"
    );

  const query =
    new URLSearchParams({
      site: domain,
    });

  return `${blockedPage}?${query.toString()}`;
}

/* -------------------------------------------------------------------------- */
/* Apply Blocking Rules                                                       */
/* -------------------------------------------------------------------------- */

export async function applyBlockingRules(
  sites: string[]
): Promise<void> {
  if (!chrome.declarativeNetRequest) {
    throw new Error(
      "Declarative Net Request API is unavailable."
    );
  }

  /**
   * Normalize and deduplicate.
   */
  const uniqueSites = [
    ...new Set(
      sites
        .map(normalizeDomain)
        .filter(Boolean)
    ),
  ];

  /**
   * Protect the dynamic-rule limit.
   */
  const limitedSites =
    uniqueSites.slice(
      0,
      MAX_DYNAMIC_RULES
    );

  /**
   * Get currently installed rules.
   */
  const existingRules =
    await chrome.declarativeNetRequest.getDynamicRules();

  /**
   * Find rules owned by Resolve.
   */
  const resolveRules =
    existingRules.filter(
      isResolveRule
    );

  const removeRuleIds =
    resolveRules.map(
      (rule) => rule.id
    );

  /**
   * No domains.
   *
   * Remove any old Resolve rules.
   */
  if (
    limitedSites.length === 0
  ) {
    if (
      removeRuleIds.length > 0
    ) {
      await chrome.declarativeNetRequest.updateDynamicRules({
        removeRuleIds,
      });
    }

    console.log(
      "🛡️ Resolve blocking list is empty."
    );

    return;
  }

  /**
   * Build Resolve redirect rules.
   *
   * Example:
   *
   * betika.com
   *
   * becomes:
   *
   * chrome-extension://EXTENSION_ID/
   * blocked.html?site=betika.com
   */
  const rules:
    chrome.declarativeNetRequest.Rule[] =
    limitedSites.map(
      (domain, index) => ({
        id:
          RESOLVE_RULE_ID_START +
          index,

        /**
         * Higher priority than ordinary
         * allow rules inside Resolve.
         */
        priority: 10,

        action: {
          type: "redirect",

          redirect: {
            url:
              buildBlockedPageUrl(
                domain
              ),
          },
        },

        condition: {
          /**
           * Domain anchor.
           *
           * Matches:
           *
           * betika.com
           * www.betika.com
           * mobile.betika.com
           * live.betika.com
           */
          urlFilter:
            `||${domain}^`,

          resourceTypes: [
            "main_frame",
          ],
        },
      })
    );

  /**
   * Replace old Resolve rules atomically.
   */
  await chrome.declarativeNetRequest.updateDynamicRules({
    removeRuleIds,
    addRules: rules,
  });

  console.log(
    `🛡️ Resolve installed ${rules.length} REDIRECT rules.`
  );

  console.log(
    "🌐 Resolve blocked domains:",
    limitedSites
  );
}